from kedro.pipeline import Pipeline, node, pipeline
from .nodes import extract_data_from_html


def create_pipeline(**kwargs) -> Pipeline:

    return pipeline(
        [
            node(
                func=extract_data_from_html,
                inputs="HTML_LargeCaps_BienesRaices",
                outputs="CSV_LargeCaps_RealState",
                name="Extract_large_caps_real_state_data_from_html",
            ),
            node(
                func=extract_data_from_html,
                inputs="HTML_LargeCaps_ConsumoDiscrecional",
                outputs="CSV_LargeCaps_ConsumerDiscretionary",
                name="Extract_large_caps_consumer_discretionary_data_from_html",
            ),
            node(
                func=extract_data_from_html,
                inputs="HTML_LargeCaps_Energia",
                outputs="CSV_LargeCaps_Energy",
                name="Extract_large_caps_energy_data_from_html",
            ),
            node(
                func=extract_data_from_html,
                inputs="HTML_LargeCaps_Financiero",
                outputs="CSV_LargeCaps_Financials",
                name="Extract_large_caps_financials_data_from_html",
            ),
            node(
                func=extract_data_from_html,
                inputs="HTML_LargeCaps_Industria",
                outputs="CSV_LargeCaps_Industry",
                name="Extract_large_caps_industry_data_from_html",
            ),
            node(
                func=extract_data_from_html,
                inputs="HTML_LargeCaps_MateriasPrimas",
                outputs="CSV_LargeCaps_Materials",
                name="Extract_large_caps_materials_data_from_html",
            ),
            node(
                func=extract_data_from_html,
                inputs="HTML_LargeCaps_ProductosDePrimeraNecesidad",
                outputs="CSV_LargeCaps_ConsumerStaple",
                name="Extract_large_caps_consumer_staple_data_from_html",
            ),
            node(
                func=extract_data_from_html,
                inputs="HTML_LargeCaps_Salud",
                outputs="CSV_LargeCaps_Healthcare",
                name="Extract_large_caps_healthcare_data_from_html",
            ),
            node(
                func=extract_data_from_html,
                inputs="HTML_LargeCaps_Servicios",
                outputs="CSV_LargeCaps_Utilities",
                name="Extract_large_caps_utilities_data_from_html",
            ),
            node(
                func=extract_data_from_html,
                inputs="HTML_LargeCaps_ServiciosDeComunicacion",
                outputs="CSV_LargeCaps_ComunicationServices",
                name="Extract_large_caps_communication_services_data_from_html",
            ),
            node(
                func=extract_data_from_html,
                inputs="HTML_LargeCaps_TecnologiasDeLaInformacion",
                outputs="CSV_LargeCaps_InformationTechnology",
                name="Extract_large_caps_information_technology_data_from_html",
            ),
            node(
                func=extract_data_from_html,
                inputs="HTML_SmallCaps_BienesRaices",
                outputs="CSV_SmallCaps_RealState",
                name="Extract_small_caps_real_state_data_from_html",
            ),
            node(
                func=extract_data_from_html,
                inputs="HTML_SmallCaps_ConsumoDiscrecional",
                outputs="CSV_SmallCaps_ConsumerDiscretionary",
                name="Extract_small_caps_consumer_discretionary_data_from_html",
            ),
            node(
                func=extract_data_from_html,
                inputs="HTML_SmallCaps_Energia",
                outputs="CSV_SmallCaps_Energy",
                name="Extract_small_caps_energy_data_from_html",
            ),
            node(
                func=extract_data_from_html,
                inputs="HTML_SmallCaps_Financiero",
                outputs="CSV_SmallCaps_Financials",
                name="Extract_small_caps_financials_data_from_html",
            ),
            node(
                func=extract_data_from_html,
                inputs="HTML_SmallCaps_Industria",
                outputs="CSV_SmallCaps_Industry",
                name="Extract_small_caps_industry_data_from_html",
            ),
            node(
                func=extract_data_from_html,
                inputs="HTML_SmallCaps_MateriasPrimas",
                outputs="CSV_SmallCaps_Materials",
                name="Extract_small_caps_materials_data_from_html",
            ),
            node(
                func=extract_data_from_html,
                inputs="HTML_SmallCaps_ProductosDePrimeraNecesidad",
                outputs="CSV_SmallCaps_ConsumerStaple",
                name="Extract_small_caps_consumer_staple_data_from_html",
            ),
            node(
                func=extract_data_from_html,
                inputs="HTML_SmallCaps_Salud",
                outputs="CSV_SmallCaps_Healthcare",
                name="Extract_small_caps_healthcare_data_from_html",
            ),
            node(
                func=extract_data_from_html,
                inputs="HTML_SmallCaps_Servicios",
                outputs="CSV_SmallCaps_Utilities",
                name="Extract_small_caps_utilities_data_from_html",
            ),
            node(
                func=extract_data_from_html,
                inputs="HTML_SmallCaps_ServiciosDeComunicacion",
                outputs="CSV_SmallCaps_ComunicationServices",
                name="Extract_small_caps_communication_services_data_from_html",
            ),
            node(
                func=extract_data_from_html,
                inputs="HTML_SmallCaps_TecnologiasDeLaInformacion",
                outputs="CSV_SmallCaps_InformationTechnology",
                name="Extract_small_caps_information_technology_data_from_html",
            ),
        ],
        tags=["html_to_csv"],
    )
