from kedro.pipeline import Pipeline, node, pipeline
from .nodes import get_sample


def create_pipeline(**kwargs) -> Pipeline:

    return pipeline(
        [
            node(
                func=get_sample,
                inputs="CSV_LargeCaps_RealState",
                outputs="CSV_LargeCaps_RealState_Sample",
                name="Extract_large_caps_real_state_sample",
            ),
            node(
                func=get_sample,
                inputs="CSV_LargeCaps_ConsumerDiscretionary",
                outputs="CSV_LargeCaps_ConsumerDiscretionary_Sample",
                name="Extract_large_caps_consumer_discretionary_sample",
            ),
            node(
                func=get_sample,
                inputs="CSV_LargeCaps_Energy",
                outputs="CSV_LargeCaps_Energy_Sample",
                name="Extract_large_caps_energy_sample",
            ),
            node(
                func=get_sample,
                inputs="CSV_LargeCaps_Financials",
                outputs="CSV_LargeCaps_Financials_Sample",
                name="Extract_large_caps_financials_sample",
            ),
            node(
                func=get_sample,
                inputs="CSV_LargeCaps_Industry",
                outputs="CSV_LargeCaps_Industry_Sample",
                name="Extract_large_caps_industry_sample",
            ),
            node(
                func=get_sample,
                inputs="CSV_LargeCaps_Materials",
                outputs="CSV_LargeCaps_Materials_Sample",
                name="Extract_large_caps_materials_sample",
            ),
            node(
                func=get_sample,
                inputs="CSV_LargeCaps_ConsumerStaple",
                outputs="CSV_LargeCaps_ConsumerStaple_Sample",
                name="Extract_large_caps_consumer_staple_sample",
            ),
            node(
                func=get_sample,
                inputs="CSV_LargeCaps_Healthcare",
                outputs="CSV_LargeCaps_Healthcare_Sample",
                name="Extract_large_caps_healthcare_sample",
            ),
            node(
                func=get_sample,
                inputs="CSV_LargeCaps_Utilities",
                outputs="CSV_LargeCaps_Utilities_Sample",
                name="Extract_large_caps_utilities_sample",
            ),
            node(
                func=get_sample,
                inputs="CSV_LargeCaps_ComunicationServices",
                outputs="CSV_LargeCaps_ComunicationServices_Sample",
                name="Extract_large_caps_communication_services_sample",
            ),
            node(
                func=get_sample,
                inputs="CSV_LargeCaps_InformationTechnology",
                outputs="CSV_LargeCaps_InformationTechnology_Sample",
                name="Extract_large_caps_information_technology_sample",
            ),
            node(
                func=get_sample,
                inputs="CSV_SmallCaps_RealState",
                outputs="CSV_SmallCaps_RealState_Sample",
                name="Extract_small_caps_real_state_sample",
            ),
            node(
                func=get_sample,
                inputs="CSV_SmallCaps_ConsumerDiscretionary",
                outputs="CSV_SmallCaps_ConsumerDiscretionary_Sample",
                name="Extract_small_caps_consumer_discretionary_sample",
            ),
            node(
                func=get_sample,
                inputs="CSV_SmallCaps_Energy",
                outputs="CSV_SmallCaps_Energy_Sample",
                name="Extract_small_caps_energy_sample",
            ),
            node(
                func=get_sample,
                inputs="CSV_SmallCaps_Financials",
                outputs="CSV_SmallCaps_Financials_Sample",
                name="Extract_small_caps_financials_sample",
            ),
            node(
                func=get_sample,
                inputs="CSV_SmallCaps_Industry",
                outputs="CSV_SmallCaps_Industry_Sample",
                name="Extract_small_caps_industry_sample",
            ),
            node(
                func=get_sample,
                inputs="CSV_SmallCaps_Materials",
                outputs="CSV_SmallCaps_Materials_Sample",
                name="Extract_small_caps_materials_sample",
            ),
            node(
                func=get_sample,
                inputs="CSV_SmallCaps_ConsumerStaple",
                outputs="CSV_SmallCaps_ConsumerStaple_Sample",
                name="Extract_small_caps_consumer_staple_sample",
            ),
            node(
                func=get_sample,
                inputs="CSV_SmallCaps_Healthcare",
                outputs="CSV_SmallCaps_Healthcare_Sample",
                name="Extract_small_caps_healthcare_sample",
            ),
            node(
                func=get_sample,
                inputs="CSV_SmallCaps_Utilities",
                outputs="CSV_SmallCaps_Utilities_Sample",
                name="Extract_small_caps_utilities_sample",
            ),
            node(
                func=get_sample,
                inputs="CSV_SmallCaps_ComunicationServices",
                outputs="CSV_SmallCaps_ComunicationServices_Sample",
                name="Extract_small_caps_communication_services_sample",
            ),
            node(
                func=get_sample,
                inputs="CSV_SmallCaps_InformationTechnology",
                outputs="CSV_SmallCaps_InformationTechnology_Sample",
                name="Extract_small_caps_information_technology_sample",
            ),
        ],
        tags=["sample"],
    )
